// source/react/src/components/Conditions.jsx
import React from 'react';
import PropTypes from 'prop-types';

import Condition from './Condition';


const Conditions = ({ conditions, city_name }) => (
  <div>
    <h3>気象検索結果:{city_name}</h3>
    <table>
      <thead>
        <tr>
          <th width="120px">日付</th>
          <th width="100px">最高気温</th>
          <th width="100px">最低気温</th>
          <th width="100px">雲量</th>
          <th width="100px">湿度</th>
          <th width="100px">降水確率</th>
          <th width="100px">気圧</th>
          <th width="100px">オゾン指数</th>
        </tr>
      </thead>
      <tbody>
        {conditions.map(condition => (<Condition key={condition.date} condition={condition} />))}
      </tbody>
    </table>
  </div>
);

Conditions.propTypes = {
  conditions: PropTypes.arrayOf(PropTypes.any),
  city_name: PropTypes.string,
};

Conditions.defaultProps = {
  conditions: [],
  city_name: '',
};

export default Conditions;

// source/vuef/src/components/Conditions.vue
<template>
  <div>
    <table class="conditions_table">
      <thead>
        <tr>
          <td>日付</td>
          <td>最高気温</td>
          <td>最低気温</td>
          <td>雲量</td>
          <td>湿度</td>
          <td>降水確率</td>
          <td>気圧</td>
          <td>オゾン指数</td>
        </tr>
      </thead>
      <tbody>
        <tr v-for="condition in conditions" :key="condition.date">
          <td>{{ condition.date }}</td>
          <td>{{ condition.temperatureMax }}</td>
          <td>{{ condition.temperatureMin }}</td>
          <td>{{ condition.cloudCover }}</td>
          <td>{{ condition.humidity }}</td>
          <td>{{ condition.precipProbability }}</td>
          <td>{{ condition.pressure }}</td>
          <td>{{ condition.ozone }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  export default {
    // props: ["conditions"],
    computed: {
      conditions(){
        return this.$store.state.conditions;
      }
    },
  }
</script>

<style scoped>
  .conditions_table > thead > tr > td {
    font-size: 16px;
    font-weight: bold;
    width: 140px;
  }
</style>
